# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import driversdb_pb2 as driversdb__pb2


class InsuranceStub(object):
  """The Insurance Server collect data by all the devices of the drivers that stipulate the contract
  """

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.Report = channel.unary_unary(
        '/Insurance/Report',
        request_serializer=driversdb__pb2.Test.SerializeToString,
        response_deserializer=driversdb__pb2.ACK.FromString,
        )
    self.initReport = channel.unary_unary(
        '/Insurance/initReport',
        request_serializer=driversdb__pb2.Test.SerializeToString,
        response_deserializer=driversdb__pb2.ACK.FromString,
        )
    self.finalReport = channel.unary_unary(
        '/Insurance/finalReport',
        request_serializer=driversdb__pb2.Test.SerializeToString,
        response_deserializer=driversdb__pb2.ACK.FromString,
        )


class InsuranceServicer(object):
  """The Insurance Server collect data by all the devices of the drivers that stipulate the contract
  """

  def Report(self, request, context):
    """A client-to-server notification RPC

    Send all data collected by an alcohol test and send an ACK to the client
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def initReport(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def finalReport(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_InsuranceServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'Report': grpc.unary_unary_rpc_method_handler(
          servicer.Report,
          request_deserializer=driversdb__pb2.Test.FromString,
          response_serializer=driversdb__pb2.ACK.SerializeToString,
      ),
      'initReport': grpc.unary_unary_rpc_method_handler(
          servicer.initReport,
          request_deserializer=driversdb__pb2.Test.FromString,
          response_serializer=driversdb__pb2.ACK.SerializeToString,
      ),
      'finalReport': grpc.unary_unary_rpc_method_handler(
          servicer.finalReport,
          request_deserializer=driversdb__pb2.Test.FromString,
          response_serializer=driversdb__pb2.ACK.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'Insurance', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
