# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: driversdb.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='driversdb.proto',
  package='',
  syntax='proto2',
  serialized_pb=_b('\n\x0f\x64riversdb.proto\"\x17\n\x03\x41\x43K\x12\x10\n\x08_result_\x18\x01 \x01(\t\"O\n\x04Test\x12\x13\n\x0b_timestamp_\x18\x01 \x02(\x04\x12\x0f\n\x07_targa_\x18\x02 \x02(\t\x12\x11\n\t_alc_lvl_\x18\x03 \x01(\r\x12\x0e\n\x06_foto_\x18\x04 \x02(\x0c\x32_\n\tInsurance\x12\x17\n\x06Report\x12\x05.Test\x1a\x04.ACK\"\x00\x12\x1b\n\ninitReport\x12\x05.Test\x1a\x04.ACK\"\x00\x12\x1c\n\x0b\x66inalReport\x12\x05.Test\x1a\x04.ACK\"\x00')
)




_ACK = _descriptor.Descriptor(
  name='ACK',
  full_name='ACK',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='_result_', full_name='ACK._result_', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=19,
  serialized_end=42,
)


_TEST = _descriptor.Descriptor(
  name='Test',
  full_name='Test',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='_timestamp_', full_name='Test._timestamp_', index=0,
      number=1, type=4, cpp_type=4, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='_targa_', full_name='Test._targa_', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='_alc_lvl_', full_name='Test._alc_lvl_', index=2,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='_foto_', full_name='Test._foto_', index=3,
      number=4, type=12, cpp_type=9, label=2,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=44,
  serialized_end=123,
)

DESCRIPTOR.message_types_by_name['ACK'] = _ACK
DESCRIPTOR.message_types_by_name['Test'] = _TEST
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ACK = _reflection.GeneratedProtocolMessageType('ACK', (_message.Message,), dict(
  DESCRIPTOR = _ACK,
  __module__ = 'driversdb_pb2'
  # @@protoc_insertion_point(class_scope:ACK)
  ))
_sym_db.RegisterMessage(ACK)

Test = _reflection.GeneratedProtocolMessageType('Test', (_message.Message,), dict(
  DESCRIPTOR = _TEST,
  __module__ = 'driversdb_pb2'
  # @@protoc_insertion_point(class_scope:Test)
  ))
_sym_db.RegisterMessage(Test)



_INSURANCE = _descriptor.ServiceDescriptor(
  name='Insurance',
  full_name='Insurance',
  file=DESCRIPTOR,
  index=0,
  options=None,
  serialized_start=125,
  serialized_end=220,
  methods=[
  _descriptor.MethodDescriptor(
    name='Report',
    full_name='Insurance.Report',
    index=0,
    containing_service=None,
    input_type=_TEST,
    output_type=_ACK,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='initReport',
    full_name='Insurance.initReport',
    index=1,
    containing_service=None,
    input_type=_TEST,
    output_type=_ACK,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='finalReport',
    full_name='Insurance.finalReport',
    index=2,
    containing_service=None,
    input_type=_TEST,
    output_type=_ACK,
    options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_INSURANCE)

DESCRIPTOR.services_by_name['Insurance'] = _INSURANCE

# @@protoc_insertion_point(module_scope)
